name: mystrio
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.3+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  share_plus: ^12.0.1
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  confetti: ^0.8.0
  file: ^7.0.1
  mime: ^2.0.0
  app_links: ^6.0.0
  path_provider: ^2.0.11
  screenshot: ^3.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.2.5
  intl: ^0.19.0 # NEW: Added intl package for date formatting
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gratitude_backgrounds/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
